#!/bin/bash

export POSIXLY_CORRECT=yes
export LC_ALL=C

set -e

# args=("$@")
count_of_args=$#
# awk '{print $1}' sort | uniq |
{
if ((4<5)); then
    awk '{ if ($1 == "ArmstrongCoin") print $0;}' cryptoexchange-5.log
fi 
} | sort -u |

{
if (( count_of_args < 5 )); then
    awk '{print $1}' | sort -u 
else 
    awk '{print $2}' sort | sort -u 
fi
} | awk '{print $0}'