#!/bin/bash
# xmikult00 Timotej Mikula
# 7.3.2024
export POSIXLY_CORRECT=yes
export LC_ALL=C

# Check for --help before getopts
if [[ $1 == "--help" || $1 == "-h" ]]; then
    echo "Hint - Help." >&2
    exit 0
fi

while getopts '' opt; do
  case $opt in
    *)  
        echo "errror invalid flag" >&2
        exit 1 ;;
  esac
done
